apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-api
  labels:
    app: contatos-grupo4
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contatos-grupo4
      tier: api
  template:
    metadata:
      labels:
        app: contatos-grupo4
        tier: api
      annotations:
        description: Pod da API de Contatos
    spec:
      containers:
      - name: contatos-api
        image: contatos/api:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: contatos-api-config
