
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-api
  labels:
    app: contatos-grupo4
    tier: api
  annotations:
    owner.team: "backend"
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contatos-grupo4
      tier: api
  template:
    metadata:
      labels:
        app: contatos-grupo4
        tier: api
    spec:
      containers:
      - name: contatos-api
        image: contatos-api:latest
        ports:
        - containerPort: 80
