
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: contatos-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contatos-api
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
