
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-api
  labels:
    app: contatos-grupo4
    tier: api
  annotations:
    maintainer: "Grupo4"
    version: "v1"
    description: "API de Contatos gerenciada via Kubernetes"
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contatos-grupo4
      tier: api
  template:
    metadata:
      labels:
        app: contatos-grupo4
        tier: api
    spec:
      containers:
        - name: contatos-api
          image: contatos-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: contatos-api-config