apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
      - job_name: 'dotnet-api'
        static_configs:
          - targets: ['contatos-api-service.default.svc.cluster.local:80']
      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq-exporter.default.svc.cluster.local:9419']