apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: contatos-grupo4
spec:
  selector:
    app: contatos-grupo4
    tier: database
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  clusterIP: None
