apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  labels:
    app: contatos-grupo4
    tier: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
