apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: contatos-grupo4
spec:
  type: NodePort
  selector:
    app: contatos-grupo4
    tier: database
  ports:
    - name: sql
      protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30007
