apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: contatos-grupo4
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatos-grupo4
      tier: database
  template:
    metadata:
      labels:
        app: contatos-grupo4
        tier: database
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "1q2w3e4r@#$"
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-data
